INSERT INTO tb_categoria(nome,descricao) VALUES ('ADMINISTRACAO','BREVE DESCRICAO DA CATEGORIA');
INSERT INTO tb_categoria(nome,descricao) VALUES ('INFORMATICA','BREVE DESCRICAO DA CATEGORIA');

INSERT INTO tb_livro(categoria_id, titulo,nome_autor,texto) VALUES (1, 'INFORMATICA BASICA','AUTOR INFORMATICA BASICA','CAMPO TEXTO');
INSERT INTO tb_livro(categoria_id, titulo,nome_autor,texto) VALUES (1, 'INFORMATICA BASICA2','AUTOR INFORMATICA BASICA 2','CAMPO TEXTO');
INSERT INTO tb_livro(categoria_id, titulo,nome_autor,texto) VALUES (2, 'ADMISTRACAO DE RECURSOS','AUTOR ADMINSITRACAO DE RECURSOS','CAMPO TEXTO');
INSERT INTO tb_livro(categoria_id, titulo,nome_autor,texto) VALUES (2, 'ADMINISTRACAO DE CONDOMINIOS','AUTOR ADMINISTRACAO DE CONDOMINIOS','CAMPO TEXTO');